### ISSUE TITLE
Telegram integration?

### ISSUE THREAD

**Issue by VozDeOuro** [Notifiarr/website#53] opened 2021-09-08 05:38 UTC
Is it possible to add a Telegram integration? would love to see that
besides discord do you have any plans for telegram as well?

**Comment by bakerboy448** [comment] 2021-09-08 06:06
Duplicate of #22

**Closed as completed by bakerboy448** 2021-09-08 06:06 UTC

**Comment by davidnewhall** [comment] 2021-09-08 10:04
Unfortunately Telegram support is a ways out...
